// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sunrise-logos/FoundationA.tsx": () => import("../components/mockups/sunrise-logos/FoundationA.tsx"),
  "./components/mockups/sunrise-logos/FoundationB.tsx": () => import("../components/mockups/sunrise-logos/FoundationB.tsx"),
  "./components/mockups/sunrise-logos/FoundationC.tsx": () => import("../components/mockups/sunrise-logos/FoundationC.tsx"),
  "./components/mockups/sunrise-logos/RecoveryA.tsx": () => import("../components/mockups/sunrise-logos/RecoveryA.tsx"),
  "./components/mockups/sunrise-logos/RecoveryB.tsx": () => import("../components/mockups/sunrise-logos/RecoveryB.tsx"),
  "./components/mockups/sunrise-logos/RecoveryC.tsx": () => import("../components/mockups/sunrise-logos/RecoveryC.tsx"),
  "./components/mockups/sunrise-recovery/Compass.tsx": () => import("../components/mockups/sunrise-recovery/Compass.tsx"),
  "./components/mockups/sunrise-recovery/Continuum.tsx": () => import("../components/mockups/sunrise-recovery/Continuum.tsx"),
  "./components/mockups/sunrise-recovery/Grove.tsx": () => import("../components/mockups/sunrise-recovery/Grove.tsx"),
  "./components/mockups/sunrise-recovery/Hearth.tsx": () => import("../components/mockups/sunrise-recovery/Hearth.tsx"),
  "./components/mockups/sunrise-recovery/Horizon.tsx": () => import("../components/mockups/sunrise-recovery/Horizon.tsx"),
  "./components/mockups/sunrise-foundation/Cradle.tsx": () => import("../components/mockups/sunrise-foundation/Cradle.tsx"),
  "./components/mockups/sunrise-foundation/Lighthouse.tsx": () => import("../components/mockups/sunrise-foundation/Lighthouse.tsx"),
  "./components/mockups/sunrise-foundation/Ripple.tsx": () => import("../components/mockups/sunrise-foundation/Ripple.tsx"),
  "./components/mockups/sunrise-foundation/RippleA.tsx": () => import("../components/mockups/sunrise-foundation/RippleA.tsx"),
  "./components/mockups/sunrise-foundation/RippleB.tsx": () => import("../components/mockups/sunrise-foundation/RippleB.tsx"),
  "./components/mockups/sunrise-foundation/RippleC.tsx": () => import("../components/mockups/sunrise-foundation/RippleC.tsx"),
  "./components/mockups/sunrise-foundation/RippleD.tsx": () => import("../components/mockups/sunrise-foundation/RippleD.tsx")
};
