// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sunrise-logos/FoundationA.tsx": () => import("../components/mockups/sunrise-logos/FoundationA.tsx"),
  "./components/mockups/sunrise-logos/FoundationB.tsx": () => import("../components/mockups/sunrise-logos/FoundationB.tsx"),
  "./components/mockups/sunrise-logos/FoundationC.tsx": () => import("../components/mockups/sunrise-logos/FoundationC.tsx"),
  "./components/mockups/sunrise-logos/RecoveryA.tsx": () => import("../components/mockups/sunrise-logos/RecoveryA.tsx"),
  "./components/mockups/sunrise-logos/RecoveryB.tsx": () => import("../components/mockups/sunrise-logos/RecoveryB.tsx"),
  "./components/mockups/sunrise-logos/RecoveryC.tsx": () => import("../components/mockups/sunrise-logos/RecoveryC.tsx")
};
